{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name')|replace("tethysapp-", "")|lower %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

about:
  author: {{ data.get('author')}}
  description: {{ data.get('description')}}
  license: "{'name': 'release_package', 'version': '2.0', 'description': 'A tool for retrieving liquefaction hazard parameters in the Unites States', 'long_description': 'A tool for retrieving liquefaction hazard parameters based on Standard or Cone Penetration Tests', 'author': 'Riley Hales, Tylor Bayer, Kevin Liang', 'author_email': '', 'url': '', 'license': 'BSD Clear 3 Clause'}"
  dev_url: {{ data.get('url') }}

outputs:
  - name: {{ name }}
extra:
  author_email: ''
  keywords:
  - Liquefaction
  - Geotechnical
  recipe-maintainers:
  - TethysAppWarehouse

build:
  noarch: python
  preserve_egg_dir: true
  script: python setup.py install --record=record.txt
requirements:
  build:
  - python
  run:
  - numpy
  - pandas
source:
  path: ..
